// Code generated by ent, DO NOT EDIT.

package runtime

// The schema-stitching logic is generated in github.com/rotemtam/ent-versioned-migrations-demo/ent/runtime.go

const (
	Version = "v0.11.5-0.20221114115835-8a8c72f37723"           // Version of ent codegen.
	Sum     = "h1:Y/PAU/KIZm6eYqsDsAHofe9+pes3H8TDeBgkILF/vBk=" // Sum of ent codegen.
)
