// Code generated by ent, DO NOT EDIT.

package ent

import (
	"time"

	"github.com/rotemtam/ent-versioned-migrations-demo/ent/blog"
	"github.com/rotemtam/ent-versioned-migrations-demo/ent/schema"
)

// The init function reads all schema descriptors with runtime code
// (default values, validators, hooks and policies) and stitches it
// to their package variables.
func init() {
	blogFields := schema.Blog{}.Fields()
	_ = blogFields
	// blogDescCreatedAt is the schema descriptor for created_at field.
	blogDescCreatedAt := blogFields[2].Descriptor()
	// blog.DefaultCreatedAt holds the default value on creation for the created_at field.
	blog.DefaultCreatedAt = blogDescCreatedAt.Default.(func() time.Time)
}
